data: 
  - 
    name: "youtube_v1"
    type: json
    path: "../../data/llava-video/data/0_30_s_youtube_v0_1/0_30_s_youtube_v0_1_cap_processed_train.conv.json"
    format: chat_video
    split: train
    max_num_frames: 32